import type { Metadata } from "next";
import localFont from "next/font/local";
import { Fredoka  } from 'next/font/google';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const fredoka = Fredoka({
  subsets: ['latin'], // Escolha os subsets que precisa
  weight: ['300', '400', '500', '600', '700'], // Inclua todos os pesos disponíveis
  variable: '--font-fredoka', // Defina uma variável CSS opcional
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-indigo-950`}
      >
        <h1 className="text-center text-4xl font-bold text-slate-100">GitHub Finder</h1>
        {children}
      </body>
    </html>
  );
}
